/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krishchandarana
 */
public class PatientPortal extends javax.swing.JFrame {

    private MyHashTable theMainHashTable;
    
    public void setTheMainHashTable(MyHashTable theRefValueHT){
        theMainHashTable = theRefValueHT;
    }
    
    public PatientPortal() {
        initComponents();
        employeeNotAdded.setVisible(false);
        employeeAdded.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeEditingPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        InputEmpNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        ExitProgram = new javax.swing.JButton();
        addPatient = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        InputFirstName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        employeeAdded = new javax.swing.JLabel();
        employeeNotAdded = new javax.swing.JLabel();
        InputLastName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        InputGender = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InputSK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        InputDOB = new javax.swing.JTextField();
        InputAllergies = new javax.swing.JTextField();
        InputMedicalConditions = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        EmployeeEditingPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Allergies:");

        InputEmpNum.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputEmpNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmpNumActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Date Of Birth:");

        jTextField5.setBackground(new java.awt.Color(255, 99, 71));

        ExitProgram.setBackground(new java.awt.Color(255, 255, 255));
        ExitProgram.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ExitProgram.setText("Back");
        ExitProgram.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        ExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgramActionPerformed(evt);
            }
        });

        addPatient.setBackground(new java.awt.Color(255, 255, 255));
        addPatient.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addPatient.setText("Add Info To The System");
        addPatient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 71), 1, true));
        addPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setText("Patient Number:");

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setText("First Name:");

        InputFirstName.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFirstNameActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel12.setText("Please enter in the following format: DDMMYYYY");

        employeeAdded.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        employeeAdded.setText("You Have Been Succesfully Added!");

        employeeNotAdded.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        employeeNotAdded.setText("Patient number in use please change it or please fill out all fields.");

        InputLastName.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputLastNameActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setText("Last Name:");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel15.setText("  Please input a six digit numerical number of your choice.");

        InputGender.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputGenderActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel16.setText("Gender:");

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Medical Conditions:");

        InputSK.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSKActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setText("Security Key:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel14.setText("Please chose a phrase to use for validation purposes.");

        InputDOB.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDOBActionPerformed(evt);
            }
        });

        InputAllergies.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAllergiesActionPerformed(evt);
            }
        });

        InputMedicalConditions.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        InputMedicalConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputMedicalConditionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeEditingPanelLayout = new javax.swing.GroupLayout(EmployeeEditingPanel);
        EmployeeEditingPanel.setLayout(EmployeeEditingPanelLayout);
        EmployeeEditingPanelLayout.setHorizontalGroup(
            EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputMedicalConditions)
            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(InputEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                        .addComponent(InputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16))
                            .addComponent(InputGender, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(InputAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                        .addComponent(addPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeAdded)
                    .addComponent(employeeNotAdded)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(InputSK, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeEditingPanelLayout.setVerticalGroup(
            EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeEditingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                        .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmployeeEditingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(InputGender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputMedicalConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputSK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EmployeeEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeNotAdded)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeAdded)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeEditingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeEditingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputEmpNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmpNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmpNumActionPerformed

    private void ExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgramActionPerformed
        // TODO add your handling code here:
        dispose();
        theMainHashTable.saveFile("TheArchive.txt");
    }//GEN-LAST:event_ExitProgramActionPerformed

    private void addPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientActionPerformed
        // TODO add your handling code here:
        //The employee is added to the hash table
        PatientInfo thePatient;

        //checking if the inputs using textfields are null
        if ("".equals(InputEmpNum.getText()) || "".equals(InputFirstName.getText()) || "".equals(InputLastName.getText()) || "".equals(InputDOB.getText()) || "".equals(InputGender.getText()) || "".equals(InputAllergies.getText()) || "".equals(InputMedicalConditions.getText()) || "".equals(InputSK.getText())) {
            employeeNotAdded.setVisible(true);
        }
        else {
            employeeNotAdded.setVisible(false);

            //Input For Each Text Field
            //Input For employee number
            String employeeNumberString = InputEmpNum.getText();
            int patientNumber = Integer.parseInt(employeeNumberString);
            PatientInfo checkIfInTable = theMainHashTable.searchFromTable(patientNumber);

            //Input For first name
            String patientFirstName = InputFirstName.getText();

            //Input For last name
            String patientLastName = InputLastName.getText();

            //Input For Deduction Rate
            String employeeDateOfBirth = InputDOB.getText();
            int patientDateOfBirth = Integer.parseInt(employeeDateOfBirth);
            
            String patientAllergies = InputAllergies.getText();
            
            String patientMedicalConditions = InputMedicalConditions.getText();
            
            String patientGender = InputGender.getText();
            
            String patientSecurityKey = InputSK.getText();
            
            if (checkIfInTable != null){
                employeeNotAdded.setVisible(true);
                employeeAdded.setVisible(false);
            }
            
            else {
                thePatient = new PatientInfo(patientNumber, patientFirstName, patientLastName, patientAllergies, patientMedicalConditions, patientGender, patientDateOfBirth, patientSecurityKey);
                theMainHashTable.addEmployee(thePatient);
                employeeAdded.setVisible(true);
                employeeNotAdded.setVisible(false);
            }
                    
        }
    }//GEN-LAST:event_addPatientActionPerformed

    private void InputFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFirstNameActionPerformed

    private void InputLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLastNameActionPerformed

    private void InputGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputGenderActionPerformed

    private void InputSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputSKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputSKActionPerformed

    private void InputDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDOBActionPerformed

    private void InputAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAllergiesActionPerformed

    private void InputMedicalConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputMedicalConditionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputMedicalConditionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeEditingPanel;
    private javax.swing.JButton ExitProgram;
    private javax.swing.JTextField InputAllergies;
    private javax.swing.JTextField InputDOB;
    private javax.swing.JTextField InputEmpNum;
    private javax.swing.JTextField InputFirstName;
    private javax.swing.JTextField InputGender;
    private javax.swing.JTextField InputLastName;
    private javax.swing.JTextField InputMedicalConditions;
    private javax.swing.JTextField InputSK;
    private javax.swing.JButton addPatient;
    private javax.swing.JLabel employeeAdded;
    private javax.swing.JLabel employeeNotAdded;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
